services:
  database:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    ports:
      - 8005:8000
    volumes:
      - /Users/xiaoyou/app/index/database:/data
    command:
      - start
      - --user=xiaoyou
      - --pass=xiaoyou
      - rocksdb:/data
  data:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 8006:9000
      - 8007:9001
    environment:
      MINIO_ROOT_USER: xiaoyou
      MINIO_ROOT_PASSWORD: xiaoyou66
    volumes:
      - /Users/xiaoyou/app/index/data:/data
    privileged: true
    command: server --console-address ":9001" /data



